### ISSUE TITLE
Shortcode [mc4wp_form] should be ignored in form content

### ISSUE THREAD

**Issue by haleeben** [ibericode/mailchimp-for-wordpress#187]
Hi

I made some changes to the form code and added an onclick event in the submit input to track with Google analytics. 

I put the shortcode name as the label '[mc4wp_form]' and having the square brackets caused the server cpu and memory to sky rocket resulting in 503 server errors.

Here is the code that caused the error

` <input type="submit" value="Sign up" onclick="ga('send', 'event', 'MailChimp Signup', 'click','[mc4wp_form]',0);"/> `

Removing the square brackets fixed the issue.

**Comment by dannyvankooten** [comment]
Hi @haleeben,

The form mark-up currently supports the use of shortcodes, allowing you (for example) to use a column plugin to add columns to your form mark-up.

However, if you use `[mc4wp_form]` in the form mark-up then the code will end up in an infinite loop because the shortcode output contains another call to its own shortcode, restarting the process. This goes on until your server has enough and calls it quit.

We'll make sure that `[mc4wp_form]` is ignored in the form content but for now, your best bet is indeed to use another identifier.

Thanks for the heads up!

**Comment by haleeben** [comment]
Thanks for the explaination, I doubt anyone else would do this but you never know.
