### ISSUE TITLE
Unable to deselect Custom integration

### ISSUE THREAD

**Issue by jphorn** [ibericode/mailchimp-for-wordpress#194]
I am unable to deselect 'Custom' in Integrations.
Is this by design?

![Unable to deselect Custom](http://d.textopus.nl/HXwMTeI8mW8hkRY3D8Tn.png)

Screen: admin.php?page=mailchimp-for-wp-integrations

**Comment by dannyvankooten** [comment]
Hey @jphorn , thanks for your (very helpful!) feedback. :-)

This is indeed by design but could definitely do with some improvements. 

Certain integrations are simply always enabled as it requires a manual action for them to work. 

In this case, the "Custom" integration aims to integrate with third-party HTML forms on your site which requires you to add a few lines of HTML to that form before it works.

I improved on this by adding a help text when you hover the disabled checkbox.

![image](https://cloud.githubusercontent.com/assets/885856/11263213/0d0959c8-8ebb-11e5-97db-b861e4b919b2.png)

Thanks again!
