### ISSUE TITLE
Connection error to mailchimp

### ISSUE THREAD

**Issue by numerosept** [ibericode/mailchimp-for-wordpress#219]
Hi, since last update i get the folllowing notice:
Error connecting to MailChimp: SSL certificate problem, verify that the CA cert is OK. Details: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed. 

Is there any problem with my host account or is it related to the plugin.

Thanks a lot.

**Comment by iMazed** [comment]
Hey numerosept,

Thanks for opening up a ticket! We have indeed encountered this issue since the 4.4 update, and seems to be a WordPress core issue. As a (temporary) fix, please add the following to your functions.php file:

`add_filter( 'http_request_args', function( $args ) {
 $args['sslverify'] = false; 
 return $args;
} );`

Hope that helps!

**Comment by numerosept** [comment]
great, thanks

**Comment by dannyvankooten** [comment]
Hey @numerosept, do you happen to know which CURL version your server is running? Thanks in advance! :)

**Comment by numerosept** [comment]
Hey it is v   7.15.5

**Comment by numerosept** [comment]
thanks a lot..
