### ISSUE TITLE
Nice Frames Issue

### ISSUE THREAD

**Issue by stgeorgiew** [ibericode/mailchimp-for-wordpress#226]
Hi there,

My submission forms are not looking nice anymore after the last update of the plugin. Pls. take a look here:

http://semeistvo.bg/lead-3-стъпки-към-промяна/

I'll appreciate your advise!

Stoyan

**Comment by dannyvankooten** [comment]
Hi Stoyan,

Sorry for not getting back to you before on this. Is this issue resolved or is still persisting? I'm guessing this is because of a conflict with your theme's stylesheet, not a plugin issue in itself.

I'm closing this issue but feel free to explain the issue to me and I'll take a look for you!

**Comment by stgeorgiew** [comment]
Hi Danni,

The problem resolved by itself, while updating to the last WP-version, so it's Ok now. 

Thanks!
