### ISSUE TITLE
open styles builder error

### ISSUE THREAD

**Issue by saretsky91** [ibericode/mailchimp-for-wordpress#230]
Every time I click open styles builder it loads and then loads again right to a preview. Therefor I never have the chance to actually build a form it just redirects me to a form preview everytime.

**Comment by dannyvankooten** [comment]
Hi @saretsky91 ,

Usually this is due to a technique called "frame busting" (which really is bad practice, if you ask me), often present in so-called security plugins. Are you running one that you know of?

We know this to be a feature in a plugin called "Social Warfare" but no doubt that several other plugins offer the same thing.

While I'm not against frame busting per se, busting out of every frame really defeats the purpose. The plugin author should check whether the site loading the iframe is the same site, and if so, allow the frame. 

Hope that helps. If not, let me know!
