### ISSUE TITLE
Success Message Isn't Appearing After Submission

### ISSUE THREAD

**Issue by taastephens** [ibericode/mailchimp-for-wordpress#260]
[MailChimp form.zip](https://github.com/ibericode/mailchimp-for-wordpress/files/145695/MailChimp.form.zip)

After the recent upgrade of the plugin, the form is not showing a success message after submission. Please review attached. Thank you.

**Comment by dannyvankooten** [comment]
Hi @taastephens ,

What's in the ZIP file? Do you have a link to your site instead?

**Comment by taastephens** [comment]
A short video demonstrating the error



Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by taastephens** [comment]
Sorry, I didn’t see the second part of that email.

The link to that site is www.issglobal.eu/contact<http://www.issglobal.eu/contact>

Tiffany Stephens - Marketing Product Specialist
Intelligent Software Solutions
p. 719.452.7622| f. 719.452.7001 | main: 719.452.7000
www.issinc.com <http://www.issinc.com/> | LinkedIn: intelligent-software-solutions

**Comment by dannyvankooten** [comment]
Hi @taastephens ,

I just took a look at your form and noticed that your entire WP Admin is loaded over HTTPS, while your site is not. When submitting the form, a request is sent to your HTTPS site which in turn denies to respond because it thinks the request is coming from a different domain. This is because of your server configuration.

You'll notice that when you load your site over HTTPS, everything will work as expected: https://www.issglobal.eu/contact/ .

Two ways to fix this:

- Force `https://` for your entire site (recommended, this is by far the best solution).
- Set an `Access-Control-Allow-Origin` header by adding the following snippet of code to your `/wp-config.php` file.

```php
$origins = array( 
   'http://www.issglobal.eu',
   'https://www.issglobal.eu',
);
$http_origin = $_SERVER['HTTP_ORIGIN'];

if( in_array( $http_origin, $origins ) ) {
   header("Access-Control-Allow-Origin: $http_origin");
}
```

Hope that helps. If not, let me know!
