### ISSUE TITLE
Plugin is exposing emails in debug log

### ISSUE THREAD

**Issue by slaFFik** [ibericode/mailchimp-for-wordpress#281]
The file `wp-content/uploads/mc4wp-debug.log` displays users emails in such format:

```
[2016-03-21 20:06:53] WARNING: Comment Form > email@example.com is already subscribed to the selected list(s)
```

I'm pretty sure that this info should not be publicly available. Save to DB?

**Comment by BurlesonBrad** [comment]
add an .htaccess to the folder and lock it down :open_mouth:

**Comment by dannyvankooten** [comment]
Hi @slaFFik,

You're absolutely right but saving this to the database would bypass a lot of the pro's of having this sort of information in a plaintext file, for example when people are using advanced log monitoring software such as PaperTrail.

We'll improve on the defaults in the plugin so that by default, no data leaks. As a quick workaround, please consider either one of the following measures.

1. If on Apache, deny access to all `.log` files (always a good idea).

```conf
<Files ~ "^.*\.(LOG|log)">
    Order allow,deny
    Deny from all
    Satisfy All
</Files>
```

If you're on NGINX, use the following to disallow access to all `.php` and `.log` files in your uploads directory.

```conf
location ~* /(?:uploads|files)/.*\.(?:php|log)$ {
	deny all;
	access_log off;
	log_not_found off;
}
```

2. Move the debug log to a protected location, outside of your web folder.

```php
add_filter( 'mc4wp_debug_log_file', function( $file ) {
   return '/var/log/mc4wp-debug.log';
});
```

3. Disable all debug logging

```php
add_filter( 'mc4wp_debug_log_level', function() { return 999; } );
```
