### ISSUE TITLE
Contact Form 7 issue

### ISSUE THREAD

**Issue by Mac2345** [ibericode/mailchimp-for-wordpress#305]
Whenever (for testing purposes) I add an email address to my form with "Subscribe me for the Newsletter" checked, I get an error stating "There was an error trying to send your message. Please try again later."
I've used Mailchimp Contact Form 7 integration.
![mail](https://cloud.githubusercontent.com/assets/18332624/15866618/0bc47f26-2cfd-11e6-8ab2-aa66efbdadd9.png)

**Comment by dannyvankooten** [comment]
Hi @Mac2345,

Ugh, that is weird. Does your PHP error log show any errors for us to work with? If you leave the "sign up for our newsletter" ckecbox unchecked, things work as expected?

Thanks in advance!

**Comment by Mac2345** [comment]
It doesn't work as it should even with the check box left unchecked.
Nothing in the error log either

**Comment by dannyvankooten** [comment]
Hi @Mac2345 ,

Since it doesn't work without our checkbox checked either, this is not an issue with our plugin but rather with Contact Form 7 itself. Most likely, your server isn't configured to send email but this is just a wild guess. You'll be better off looking through the Contact Form 7 support forums or asking there, since we didn't develop that plugin.

Sorry I can't be of more help, but good luck in fixing this.

**Comment by Mac2345** [comment]
I will, thank you
