### ISSUE TITLE
Subscribe form not working

### ISSUE THREAD

**Issue by ehogsten** [ibericode/mailchimp-for-wordpress#325]
I just tested the subscribe widget on my website elizabethhogsten.com, and I got an error message saying the page could not be found. It worked fine in the beginning (because I tested it back then with a different email address), but I have no idea how long it may have been broken. (None of the other forms on my posts or pop-ups work either.) The problem didn't show up in the error log either. 

Any help would be greatly appreciated!

**Comment by dannyvankooten** [comment]
Hi @ehogsten,

I'm terribly sorry for not getting back to you any sooner. Are you still having this issue and if so, could you show us a link to your site? Since this is most likely an implementation issue and not an issue with the plugin code a better place to ask for help would be the plugin's support forums on WordPress. That will get you a much faster reply than here, as I can be quite slow (sorry).
