### ISSUE TITLE
'close' button not working on my mail chimp popup on mobile devices

### ISSUE THREAD

**Issue by bybreharne** [ibericode/mailchimp-for-wordpress#348]
I've had some feedback this morning that the 'close' button on my popup is not working on mobiles. So, no one on a mobile device can actually navigate through my site because the popup won't close. I regenerated the mail chimp code and re applied it to my site but no change. Can anyone help me to fix this please?

**Comment by dannyvankooten** [comment]
Hi there,

Our plugin does not provide pop-up functionality so this really depends on the pop-up method / plugin you're using. Are you using Boxzilla by any chance?

If not, please contact the relevant plugin author. Otherwise, feel free to share a link to your site here and I'll try to take a look.
