### ISSUE TITLE
PHP Notice:  Undefined index: settings

### ISSUE THREAD

**Issue by sumobi** [ibericode/mailchimp-for-wordpress#356]
Hey Danny! 

Just installed this for the first time. I created a new form and saw this error in both master and the version on .org:

```
PHP Notice:  Undefined index: settings in /wp-content/plugins/mailchimp-for-wordpress/includes/forms/class-admin.php on line 142
```

When you update the form (after adding it) the settings meta key/value pair is created fine. 

It looks like you don't need this line when first creating the form since the settings key does not exist:

https://github.com/ibericode/mailchimp-for-wordpress/blob/master/includes/forms/class-admin.php#L142

**Comment by dannyvankooten** [comment]
Hey @sumobi, good to see you here.

Did you select a list in the form settings on the "Add form" page or did you not yet connect to MailChimp? I believe this notice is due to the fact that no `settings` key will be present in the POST variables since we're using checkboxes for the lists, so we should take that into account when calling `update_post_meta`.

**Comment by sumobi** [comment]
If I remember correctly, I added a form without first connecting to MailChimp

**Comment by dannyvankooten** [comment]
Thanks @sumbo, that makes sense. The call to `update_post_meta` will still be needed for people that want to set a list right away when creating their first form (after they've connected), but this is a great catch. Thank you for reporting it!

**Comment by sumobi** [comment]
Got it, no problem! 👍
