### ISSUE TITLE
Mailchimp for Wordpress Form is Submitting Google Form

### ISSUE THREAD

**Issue by conselman** [ibericode/mailchimp-for-wordpress#368]
I have the mailchimp for wordpress shortcode in a widget in the sidebar of my page. When someone fills it out and presses submit it tries to submit the Google Form that is on the same page, and since this form has required fields it takes them to a page to prompt them to fill in those fields. I switched to this plugin because I was having the same problem with the embed feature in mailchimp.
http://gigharboreagles.com/harbor-happenings/

**Comment by dannyvankooten** [comment]
Hi @conselman ,

How are you including the form on your site? Are you using the shortcode or widget?

**Comment by conselman** [comment]
The form is in an Iframe.

**Comment by dannyvankooten** [comment]
Sorry for not getting back to you earlier @conselman, but since you were having the same issues with the default MailCHimp embed form I reckon this is due to an unclosed HTML tag somewhere on your page. I suggest running your page's HTML source through the W3 HTML validator to get an idea of where to look.
