### ISSUE TITLE
MailChimp for WordPress Premium suddenly blocks logins to the WP dashboard/admin login??

### ISSUE THREAD

**Issue by LeahKMurray** [ibericode/mailchimp-for-wordpress#399]
Hi, folks,

I am the web developer and tech support person for the web domain http://www.cricklewood.ca, which is owned by Beth & Brent Siwicky to help market their orchard, produce farm and corn maze, Cricklewood Farm.  

We are using WordPress 4.6.1 running Business Identity theme Version: 2.0.0 with MailChimp for WordPress Version 4.0.11 and MailChimp for WordPress Premium Version 3.3.4.

We updated our MailChimp plugins yesterday along with two other plugins that are not currently actively in use on our WordPress installation, only to find that our MailChimp for WordPress Premium Version 3.3.4. plugin had disabled our admin login on the WordPress installation.   

Our ISP was able to go in on their server end and disable the plugin for us, so now we can log in again, BUT we use this plugin for several important forms that are running on the site.  

As long as the plugin is down, none of our forms are working properly.   

How do we find support for this issue?   We do need to resolve whatever conflict has raised its head here as soon as we efficiently can.

Many thanks for any assistance you can provide!

Leah Murray

**Comment by dannyvankooten** [comment]
Hi Leah,

Where there any errors when the WP Admin section of the site was blocked? If you were seeing a "white screen of death" then it means something in the site's code (probably in the Premium plugin) caused a so-called "fatal error". Your PHP error log should show this error so that we know exactly what went wrong.

There are no known compatibility issues with MailChimp for WordPress version 4.0.11 and the Premium add-on version 3.3.4, so it's hard to say what could be causing this without seeing the error message.

Do you happen to know what PHP version your site's server is running?

Let us know please - we'd love to help out! Please know that as you're a Premium customer, you could also email us at support@mc4wp.com which should get you a somewhat faster reply from one of our team members.

**Comment by dannyvankooten** [comment]
Hi Leah,

To add to my previous email, we actually found an issue affecting people still running PHP 5.2 on their sites. We have just pushed out version 3.3.5 of the Premium plugin which fixes this issue, so I have a feeling this might fix it for you as well.

Please note that if you're running PHP 5.2 then your site is at risk, since it is over 6 years old and no longer getting any security or performance updates. Simply updating your PHP version to a more recent version (7.0+) will greatly improve the performance of your site as well, so I highly recommend looking into that.

Let us know if version 3.3.5 does not fix the issue for you please.

**Comment by LeahKMurray** [comment]
Hi, Danny!

 

Just wanted to let you know that this definitely did the job for us!

 

Thanks a million for your prompt and effective response!

 

Have a lovely holiday season with celebrations exactly to your taste, and may the New Year bring more of the same.

 

Leah Murray

**Comment by dannyvankooten** [comment]
Hi Leah,

I'm glad to hear it! Thanks for letting us know. Thanks for the wishes and
right back at you, have a lovely Christmas and 2017!
