### ISSUE TITLE
WordPress and MailChimp - subscsriptions, forms not pulling

### ISSUE THREAD

**Issue by Cblaw2** [ibericode/mailchimp-for-wordpress#423]
Received the below email from WordPress. 

1.  Can anyone assist what this email means? 
2.  Email popup with Ninja Popups not triggering an auto email reply from Mail Chimp. Can anyone assist?

===============================

New subscription on 
IMPORTANT! You have received this message because connection to your e-mail marketing software failed. Please check connection setting in the plugin configuration.
boswell.christopher@gmail.com has signed up to a lot of lists very recently; we're not allowing more signups for now 

E-mail: boswell.christopher@gmail.com
Name: --

Form: GKIC &#8211; SuperConference 2017 &#8211; PopUp for Entrepreneurs (621)

Referer: https://chrisboswelllaw.com/
Date: 2017-03-29 20:23
IP: 72.239.21.203
=============================

**Comment by arnelap** [comment]
Hi, 

Please take a look at https://mc4wp.com/kb/solving-connectivity-issues/ if you are really having issues connecting to MailChimp API (there will be an error visible on the MailChimp for WP "MailChimp" settings pages).

But the error that is copied to the email is not about the connection with MailChimp, but about MailChimp blocking that specific email from signing up because that email is used to sign up to too many lists in a shot time. You can contact MailChimp support for more information on that. 

Please contact support via http://wordpress.org/support/plugin/mailchimp-for-wp if you need any help with the MailChimp for Wordpress plugin.

I will close this issue as it is not development related.
