### ISSUE TITLE
custom integration form interception priority

### ISSUE THREAD

**Issue by drzraf** [ibericode/mailchimp-for-wordpress#424]
Hi
I wondered why mailchimp-for-wordpress would not grab an _mc4wp-subscribe-_enabled Give custom form.
After digging further I found that the hook is explicitly set to a low (90) priority which make it useless for the purpose it intends to serve.
https://github.com/ibericode/mailchimp-for-wordpress/commit/36c52122b54cebf5f7f085a1648760f6e32013e1#diff-a3293478968ba03d43c6a03ca0946c73L22

See the code: https://github.com/ibericode/mailchimp-for-wordpress/blob/master/integrations/custom/class-custom.php#L30

At the very least, if a given MC form is intended to give the hand back to the original form (what most custom forms would do), then the class should hook rather soon than late.
But we can't even test that without actually looking at form's data.
So in the end the question is: what's the point in hooking so late?

**Comment by dannyvankooten** [comment]
That is actually intended behavior. Because integrations hook into another form, the main goal of that form is to perform that action. 

With checkout forms and user registration forms it is more important to capture the data correctly first & ensure the transaction succeeds before even attempting to subscribe to MailChimp. That's why we hook in pretty "late".

Why is this late priority not working for Give or what are you intending to do? We might be able to come up with a workaround or different method for you.
