### ISSUE TITLE
currency information not transmitted

### ISSUE THREAD

**Issue by guyug** [ibericode/mailchimp-for-wordpress#430]
My woocommerce store works with different currencies and all amounts are transmitted to my MailChimp account in the base currency, without applying any exchange rates.
So for a purchase of $ 590 MXN (Mexican pesos) in my store, in MailChimp it registers as € 590 euros, which is quite a difference!!

**Comment by dannyvankooten** [comment]
Hi @guyug,

I'm afraid that while we do send currency information for each order individually, MailChimp does not yet take this into account in their web interface. Since they have the API part of this functionality working, I presume they will be adding support for multi-currency stores soon but it would be best to get in touch with them and ask them about it, they might be able to enable it for your account a little sooner.
