### ISSUE TITLE
How to make the form responsive?

### ISSUE THREAD

**Issue by designbysara** [ibericode/mailchimp-for-wordpress#443]
Hello,
The forms look bad on mobile. It is not responsive. Can you please tell me how to make these responsive? http://2c1.359.myftpupload.com/

**Comment by dannyvankooten** [comment]
Hi @designbysara,

If you go into your form settings and open up the "Appearance" tab, loading any of the included stylesheets that come with the plugin should make your form responsive. This depends on your theme as well though.

If you're using the Styles Builder that comes with the plugin, make sure you're using a `%` value instead of a `px` value. It seems like you use "500px" in your settings, changing this to a percentage based value should work better.

Hope that helps. If not, let us know please!
