### ISSUE TITLE
Urgent, error after updating to 4.1.7

### ISSUE THREAD

**Issue by WPJobs** [ibericode/mailchimp-for-wordpress#474]
Hey! Please fix, it happens after updating to the latest version

Fatal error: Class ‘WPForms_Field’ not found in \wp-content\plugins\mailchimp-for-wp\integrations\wpforms\class-field.php on line 11

please fix ASAP

i don't have WP Forms plugin installed, latest WP version

**Comment by dannyvankooten** [comment]
Hey @WPJobs,

Ugh, I am sorry about that happening. Please deactivate the plugin by renaming the plugin folder in `/wp-content/plugins/mailchimp-for-wp` and then install the latest update we just pushed out, version 4.1.8. That should get rid of the issue.

Fixed by d350cac62d2bdcf845b6e32ef63ef2caead08ed6
