### ISSUE TITLE
MailChimp non-required fields showing as required.

### ISSUE THREAD

**Issue by dreppun** [ibericode/mailchimp-for-wordpress#480]
My website URL: www.ffvhc.org

### How can we reproduce this issue?
1.
2.
3.

### Technical info
* WordPress version:
* MailChimp for WordPress version:
* Relevant plugins in case of a bug:

**Comment by dannyvankooten** [comment]
Hi @dreppun,

That's because the MailChimp address fields does not accept partial address info, so in order for the address field to work properly all of the various address part fields have to be filled.

If you want to capture just a part of the address (eg city) then we recommend adding a "text" field to your MailChimp list.

Hope that clarifies!
