### ISSUE TITLE
When user is logged in as admin and no list is set, include a link to form settings in the error.

### ISSUE THREAD

**Issue by arnelap** [ibericode/mailchimp-for-wordpress#495]
When user is logged in as admin and no list is set, include a link to form settings in the error on the visitor side of things.

**Comment by dannyvankooten** [comment]
Just added this. We used to do this before version 3.0 as well (nearly 2 years ago now), and got a lot of questions for people how to get rid of that link because they thought visitors would see it too. So we added even more text to it, explaining that visitors did not see that text, lol... Let's try again.

**Comment by arnelap** [comment]
"To hide this text, set the form to point to a list, because now it's not working". :)
