### ISSUE TITLE
Improved form validation (using MailChimp field types)

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/mailchimp-for-wordpress#499]
In order to properly tackle #498 we should refactor the form validation process so that the MailChimp field types are taken into account. We are formatting the data according to the field types MailChimp expects right now, so we should probably just move that a little forward in the process lifecycle.

**Comment by mohammedmousa1** [comment]
Hello,
Please look for my website [اlive24ksa](https://live24ksa.com).
You will see a MailChimp sign up form on the left side.
The problem is that when the visitor subscribes to the list, he must go to his email and verify it.
I do not like it and want it to be easier for my visitors.
You know that most visitors do not like verifying methods and requesting speed in achieving their needs. 
Can you tell me what I can do?
Note/ the MailChimp pop up and the signup form created on my Mailchimp account itself do not require this step.
Regards.
