### ISSUE TITLE
MailChimp API error: 400 Bad Request. mo******@gm***.com has signed up to a lot of lists very recently; we're not allowing more signups for now

### ISSUE THREAD

**Issue by ryanp210** [ibericode/mailchimp-for-wordpress#506]
My website URL: 

### The issue
MailChimp API error: 400 Bad Request. mont****@gm***.com has signed up to a lot of lists very recently; we're not allowing more signups for now

- Is there a way I can view the email that attempted to sign up? Unfortunately, we had about 60+ email signups when this bug was going around, is there a way I can manually find these addresses and add them to our lists? 

### How can we reproduce this issue?
1. Need previous version of MailChimp plugin
2.
3.

### Technical info
* WordPress version:4.9.1
* MailChimp for WordPress version: 4.1.9
* Relevant plugins in case of a bug:

Thank you!

**Comment by dannyvankooten** [comment]
Hi @ryanp210,

Usually the email addresses that are blocked because of signing-up to too many list in a short timeframe are spam bots, so I would not take the effort of adding these to your list manually. These blocks are also only affecting the email address in question, so other email addresses should be able to sign-up to your list just fine (provided that the other email addresses are not spam bots which are also blocked).

Therefore no manual action should be needed on your side of things, as only bots are prevented from signing up to your list.

How do you know that 60+ sign-ups happened, by looking at the debug log that ships with the plugin?

**Comment by ryanp210** [comment]
Hi @dannyvankooten 

Thank you for your swift reply! Originally I thought it was a bug because some googling revealed I was not the only one with this problem - [link](https://wordpress.org/support/topic/mailchimp-api-error-400-bad-request/)

I have attached the error log -- it is a txt file. 

I looked at the addresses and cross-referenced some of the accounts to names on our facebook and was able to manually match a few emails. I was wondering if there is a local database where I can see the emails to determine whether or not the remaining are fake. 

How do you think I should proceed? Do the ones attached look fake? Or is it worth further investigation? 

Thank you


[Error Log.txt](https://github.com/ibericode/mailchimp-for-wordpress/files/1560357/Error.Log.txt)

**Comment by dannyvankooten** [comment]
Hi @ryanp210,

I'm afraid there isn't unless you are using our Premium add-on plugin, which stores each successful sign-up attempt in your local WordPress database so that the data can be retrieved whenever you want. The free version however does not do this.

Personally I wouldn't worry about the dropped sign-ups. MailChimp usually does not block an email address from subscribing to your list without good reason and if it really is a valid human trying to sign-up to your list, they most likely ended up on your list anyway (eg by contacting you or trying at another time). 

That said, since your logs indicate that you were at least experiencing some kind of bot "attack" in July, do you have double opt-in enabled for the selected MailChimp list that that form is subscribing to?

**Comment by ryanp210** [comment]
Acknowledged. Thank you!

And I actually just turned it off today to make sure the emails were going through to the correct account. However, I will re-enable this!

**Comment by dannyvankooten** [comment]
That's what I would recommend @ryanp210. 👍  We're big believers in quality over quantity and have found that double opt-in really helps in keeping your lists clean!
