### ISSUE TITLE
Required field is missing error when all required fields filled in

### ISSUE THREAD

**Issue by AMMSSIT** [ibericode/mailchimp-for-wordpress#510]
My website URL: https://madaboutmarriage.com/seminars/

### The issue
Even though user fills out the entire form, form does not submit and produces this error: "Please fill in the required fields".  All fields are filled; all required fields are filled.  I've isolated the error to the Address field (which includes Street Address, City, State, Zip and Country).  Whether the corresponding Address field in Mailchimp is required or not, the same error is produced.  Users alerted us to this issue on 12/21/2017, don't know how long this has been happening.  This form has been live for over a year with no error of this kind until now.  

### How can we reproduce this issue?
1. I will be making the Address field into separate text fields on Mailchimp, as this site is live and the form needs to be working, so the error cannot be reproduced on our site. To reproduce error, create an Address type of field in a Mailchimp form.  
2. Then add that Address field in Wordpress, which is actually separate fields for Street Address, City, State, Zip, and Country.
3. Submit the form. The error, "Please fill in the required fields", should occur.

### Technical info
* WordPress version: 4.9.1
* MailChimp for WordPress version: 4.1.12
* Relevant plugins in case of a bug:

**Comment by overwine** [comment]
I have this same issue.

**Comment by catwoods** [comment]
i'm having the same issue, all required fields in mailchimp are set in form and replicated in wordpress. Had a customer raise the issue to me, but at the moment I can't promote my products as purchases all stem from the registration form.

**Comment by LadyBry** [comment]
I have this issue too - everything else works fine until the following:

- the Address field is set to 'not required' on my mailchimp list

- Form fields are not red starred on wordpress mailchimp plugin prior to placing into form.

- BUT - As soon as you add the first address field to the form, all remaining fields suddenly populate with a red outline and red star making them mandatory fields - even though they are not ticked on the insert dialogue.

- If  you delete all address fields from your form, they go back to normal with no red star.  Very strange.

I will try creating individual address fields on mailchimp to resolve but this does appear to be a bug

**Comment by LadyBry** [comment]
Also, although the fields have a red star on the form field area, the code in the form does not insert the 'required' tag

**Comment by LadyBry** [comment]
@dannyvankooten - Is this a fixable bug?  If we upgrade to pro, I'd want to make sure it was.  Thanks for your time

**Comment by arnelap** [comment]
Hi,

This error has to do with fields of the type "Address". Mailchimp is pretty strict with address verification, if part of the address is missing all will be ignored. We tried to solve this by making all the parts of the address field required, but that's not a great solution either.

Our advice is to use normal text fields for each part of the address (street, zip, country,...) instead of the "address type" field of MailChimp, that way you have full control over what is required and data will be accepted even if for example only the zip code is filled and not the country. 

We are working on this via this git issue: https://github.com/ibericode/mailchimp-for-wordpress/issues/498 that's why I will now close the issue here.

If you need support, please create a ticket on wordpress.org/support/plugin/mailchimp-for-wp

Hope that helps.
