### ISSUE TITLE
Parse error: syntax error, unexpected ')', expecting :: (T_PAAMAYIM_NEKUDOTAYIM) in .../public_html/wp-content/plugins/mailchimp-for-wp/includes/functions.php on line 69

### ISSUE THREAD

**Issue by rcvieira** [ibericode/mailchimp-for-wordpress#602]
My website URL: https://rodrigovieira.me

### The issue
After updating the plugin from wordpress plugin page the error appears in any page.

### How can we reproduce this issue?
1. Update the plugin
2. Access any page (admin or not)

### Technical info
* WordPress version: 4.9.8
* MailChimp for WordPress version: 4.3
* Relevant plugins in case of a bug:

**Comment by rcvieira** [comment]
After that, I commented the lines 69 and 71 like bellow and my site was back. 
//    if (defined('MC4WP_API_KEY') && (!empty(MC4WP_API_KEY))) {
        return MC4WP_API_KEY;
//    }

**Comment by dannyvankooten** [comment]
Ugh, I'm sorry @rcvieira. Thank you for the quick heads up, sorry for not seeing it sooner. 

We've just pushed out version 4.3.1 in which this is fixed. 

By the way, the issue was only affecting people on PHP versions older than 5.5, which hasn't been actively maintained for over 3 years now. I strongly suggest updating to a more recent PHP version.

**Comment by rcvieira** [comment]
Thank's @dannyvankooten. You were very fast fixing it.
Now I have to find out how to upgrade PHP.
