### ISSUE TITLE
Error connecting to Mailchimp: 503 Service Unavailable 

### ISSUE THREAD

**Issue by katee812** [ibericode/mailchimp-for-wordpress#625]
My website URL:  https://spreadthehealth.co/

### The issue
![image](https://user-images.githubusercontent.com/49112425/55285068-fb431280-5340-11e9-8317-e8b880b50bb0.png)

***It appears there have been several reports of this over the last 3 days***

### How can we reproduce this issue?
1.
2.
3.

### Technical info
* WordPress version:
* Mailchimp for WordPress version:
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp


It seems your hosting server IP is blocked by the MailChimp firewall. This is not something we can control, it's not our firewall or plugin doing this, it's the Akamai firewall. 

Akamai is the firewall MailChimp and many other major websites use to protect their servers, which is why this is somewhat harder to fix.

If you are on shared hosting your server IP is shared with a number of clients, it's possible that one of the other clients did something to get the IP blacklisted by the Akamai firewall. 

When this happens, we recommend you to change your IP address because having a bad reputation at Akamai does not just affect the MailChimp API.

There are various ways to go about this.
Ask your webhost for a new IP address.
Migrate to a new webhost if your hosting company is unwilling to fulfill your request.
Configure your server to connect to the MailChimp API server using a proxy.

Hope that helps. If you have any questions, please let us know!
