### ISSUE TITLE
Mailchimp blocking requests from MC4WP

### ISSUE THREAD

**Issue by Kokotai** [ibericode/mailchimp-for-wordpress#647]
My website URL: https://stickersdecalsgraphics.co.uk

### The issue
Mailchimp is blocking requests due to something suspicious. No emails are being collected by the forms. See below screenshot:
![MC4WP](https://user-images.githubusercontent.com/55602641/65355388-b6aa7c80-dbe9-11e9-89e3-5aff3536dc3e.PNG)

### How can we reproduce this issue?
1.
2.
3.

### Technical info
* WordPress version: 5.2.3
* Mailchimp for WordPress version: 4.5.5
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp

It seems your hosting server IP is blocked by the MailChimp firewall. This is not something we can control, it's not our firewall or plugin doing this, it's the Akamai firewall. 

Akamai is the firewall MailChimp and many other major websites use to protect their servers, which is why this is somewhat harder to fix.

If you are on shared hosting your server IP is shared with a number of clients, it's possible that one of the other clients did something to get the IP blacklisted by the Akamai firewall. 

When this happens, we recommend you to change your IP address because having a bad reputation at Akamai does not just affect the MailChimp API.

There are various ways to go about this.
Ask your webhost for a new IP address.
Migrate to a new webhost if your hosting company is unwilling to fulfill your request.
Configure your server to connect to the MailChimp API server using a proxy.
