### ISSUE TITLE
list_unsubscribe_delete() has been removed. Why?

### ISSUE THREAD

**Issue by strayobject** [ibericode/mailchimp-for-wordpress#659]
### The issue
list_unsubscribe_delete() has been removed.
https://github.com/ibericode/mailchimp-for-wordpress/commit/82bc00ba7065f091a93c88b902636d6af5a06885#diff-0536ed9d9554282db6ccfbcf0d115008L133

Was this accidental? If deliberate, then what's the reason behind the deletion?

This change breaks compatibility, doing so in a commit titled 'misc improvements' and on top of that not communicating it in the changelog is a rather poor form.

**Comment by dannyvankooten** [comment]
Hey @strayobject,

You're 100% right, we should have handled that better. The vast majority of our users are not developers so we mostly cater to them, but I totally agree that this is not nice.

The change is deliberate as we really prefer developers to use mostly functions and not any of the classes shipped in the plugin (which is why we marked `MC4WP_MailChimp` as private).

```php
$api = mc4wp_get_api_v3();
$api->delete_list_member($list_id, $email_address);
```

**Comment by strayobject** [comment]
Cool, thank you for the update :+1:
