### ISSUE TITLE
shortcode is not working after updating the plugin

### ISSUE THREAD

**Issue by elisasaurus** [ibericode/mailchimp-for-wordpress#664]
My website URL: 
http://carpentersmith.staging.wpengine.com/services/

### The issue
The mailchimp sign up form that is in the right column no longer shows up after updating the plugin. It now just shows the shortcode.

### How can we reproduce this issue?
1. View the page where the form should be in the right column (link above)
2. See the shortcode instead of the form itself
3. Code was not changed in anyway, only thing done was the plugin was updated

### Technical info
* WordPress version: 5.3
* Mailchimp for WordPress version: 4.7.4
* Relevant plugins in case of a bug:

**Comment by dannyvankooten** [comment]
Hello @elisasaurus,

This is because you're on an older version of WordPress. Updating to at least version 4.9 should fix the issue for you.

**Comment by elisasaurus** [comment]
My version of WordPress is 5.3

**Comment by dannyvankooten** [comment]
Hi @elisasaurus,

Huh, sorry, I really thought I read "WordPress version 4.7" but it turns out I misread that. My mistake.

e5ded13f38df6b8ce3258e497c507908a1050791 is the change that probably caused this to happen for you. These lines were added to WordPress core in version 4.9 so I am not sure why this isn't working for you. A sure way to fix it would be to re-add the following lines to your active theme its `functions.php` file.

```php
add_filter( 'widget_text', 'shortcode_unautop' );
add_filter( 'widget_text', 'do_shortcode', 11 );
```

**Comment by elisasaurus** [comment]
That fixed the issue. Thanks!
