### ISSUE TITLE
Plugin Fail to Update

### ISSUE THREAD

**Issue by Hirschj** [ibericode/mailchimp-for-wordpress#715]
My website URL:  www.aucart.com

To whom it may concern,

May we have some assistance regarding the API?
I’ve attached in the following a screenshot of our notice that our plugins have failed to update. 
We are also using version 3.4.4 WP User of Wordpress and version 1.8.12 MC4WP: Mailchimp for WordPress/Wordpress Premium plugin. 
Do let me know if I can provide anything in addition to this -
Warmest,
Joanna Hirsch 
joanna@aucart.com

![Mailchimp for WP](https://user-images.githubusercontent.com/76268844/102701886-e485d300-4229-11eb-8e96-09beb90de5a1.png)

**Comment by hchouhan** [comment]
Hey @Hirschj,

Please note that this channel is to create bug reports. For support requests in the future, please contact us using the email provided at https://www.mc4wp.com/contact/.

Regarding the issue you are facing, it's due to the license activation. If you have a valid and active license, please enter that in our plugin's settings page at "MC4WP > Others".
