### ISSUE TITLE
Variable Post ID is not detected when passed in redirect URL

### ISSUE THREAD

**Issue by hchouhan** [ibericode/mailchimp-for-wordpress#721]
When using the following redirect URL,

https://yourwebsite.com/?email={user property='user_email'}&id={post property='ID'}

The "Email" is passed but the post ID is empty.

**Comment by hchouhan** [comment]
https://secure.helpscout.net/conversation/1438492830/28670?folderId=253120

**Comment by dannyvankooten** [comment]
This is an issue with the redirect URL setting being incompatible with the `{post}` tag, especially if combined with AJAX because the AJAX endpoint doesn't know about the post that the request came from.

A workaround is to add a hidden field to the form containing the post ID. That will result in the post ID being included in the request to the AJAX endpoint, after which it can be referenced using the `{data key="FIELD_NAME"}` tag.

```html
<input type="hidden" name="POST_ID" value="{post}" />
```

Redirect URL setting:
```txt
http://website.com/?id={data key='POST_ID'}
```
