### ISSUE TITLE
Mailchimp subscription html markup in wordpress website is not sending email to customers instead directly registering inside the mailchimp audiences

### ISSUE THREAD

**Issue by imsjuv** [ibericode/mailchimp-for-wordpress#770]
My website URL: 
https://mercy4humanity.org/

### The issue
Mailchimp subscription html markup in wordpress is not sending email to customers instead directly registering inside the mailchimp audiences
### How can we reproduce this issue?
1. Browse to my website https://mercy4humanity.org/
2. Scroll to the bottom and find mailchimp subscription UI
3. Enter email address and click subscribe, it says " thanks for subscribing" and directly registers into mailchimp audiences
4. But the email address entered above is not getting any confirmation to register or not

### Technical info
* WordPress version:6.2.2
* Mailchimp for WordPress version: 6.2.2
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
If you turn off Double opt-in under MC4WP > Form > Settings, the contact will be seen as "imported" instead of "subscribed". 
I suggest you try again with double opt-in turned on in the form settings. 

We only use git for development related issues. 

For free support related to the Mailchimp for Wordpress plugin, please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
